title: "Spendlesso"
description: "Latest discount codes and simple ways to save."
baseurl: ""
url: "https://spendlesso.com"

markdown: kramdown
theme: null

collections:
  brands:
    output: true
    permalink: /brands/:name/
  coupons:
    output: true
    permalink: /brands/:path/
